
services:
  database:
    image: mariadb:11
    container_name: securevent_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: securevent
      MARIADB_USER: securevent
      MARIADB_PASSWORD: securevent
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
